# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BoundlessBrilliance' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BoundlessBrilliance

pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'Toast-Swift', '~> 4.0.0'

  target 'BoundlessBrillianceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BoundlessBrillianceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
